##############################################################################
#Introduction:Config.ini file is used to specify the modules to be collected.
#File format:
# -- Module:Log file module 
# -- flag: yes:collect no:not collect
#Description:A brief description of the module config. 
#if config flag as 'yes', the content in the module will be collected
#if config flag as 'no',the content in the module will not be colleted
#you can config the module action use config.ini in subdir
#More details please refer to user guide
##############################################################################
Module           group                flag    description
module=bmc       |group=log           |yes    |BMC module
