#!/bin/sh

if `test -f /var/enable_ipv6addr_loss_scheme`; then
    echo "Enable IPV6 Address Loss Scheme"
    interface=`grep ' inet6' /conf/interfaces | awk '{ print $2 }'`
else
    echo "Disable IPV6 Address Loss Scheme"
    interface=`grep 'iface eth' /conf/interfaces  | awk '{ print $2 }'`
fi

if [ -f  "/etc/dhcp-script" ]
then
    . /etc/dhcp-script
    #echo "AMI DHCP6 script : dhcp.conf found."
#else
    #echo "AMI DHCP6 script : dhcp.conf not found.  The extend parameters will not use."
fi

#if [ -n "$SET_DHCP_PREIP6" ];then
#    echo "AMI DHCP6 : Send requested address"
#	REQ_PRE_IP="-R $SET_DHCP_PREIP6"
#fi
if [ -f  "/conf/dns.conf" ]
then
    . /conf/dns.conf
fi

    echo " calling dhcp6c.... "
    HOST_NAME=`hostname`
#if [ -f  "/etc/dhcp-script" ];then
    if [ "$DO_DDNS" == 'yes'  -o "$DO_DDNS" == 'y' ]; then
        if [ "$SET_FQDN" == 'yes'  -o "$SET_FQDN" == 'y' ]; then
            echo "Dhcpv6 Client FQDN (Option 39)..."
            REG_BMC_HOSTNAME="-F $HOST_NAME "
        fi
    fi 
#fi

#if [ -f  "/etc/dhcp-script" ];then
#    dhcp6c -p /var/run/dhcp6c.$1.pid $1 $REQ_PRE_IP 
#else
    if `test -f /var/enable_ipv6addr_loss_scheme`; then
        echo "dhcp6c -p /var/run/dhcp6c.eth.pid $interface $REG_BMC_HOSTNAME"
        test -f /var/run/dhcp6c.eth.pid && kill `cat /var/run/dhcp6c.eth.pid`
        dhcp6c -p /var/run/dhcp6c.eth.pid $interface $REG_BMC_HOSTNAME
    else
        echo "dhcp6c -p /var/run/dhcp6c."$1".pid "$1" $REG_BMC_HOSTNAME"
        kill -9 `cat /var/run/dhcp6c.$1.pid`
        dhcp6c -p /var/run/dhcp6c.$1.pid $1 $REG_BMC_HOSTNAME
    fi
#fi

exit 0

