server.modules += ( "mod_websocket" )

websocket.timeout = 0

websocket.server = (
                     "^\/kvm" => ( "host" => "127.0.0.1",
                                           "port" => 7578,
                                           "proto" => "tcp",
                                           "type" => "binary",
                                           "subproto" => "binary"),

                     "^\/cd-server" => ( "host" => "127.0.0.1",
                                           "port" => 5120,
                                           "proto" => "tcp",
                                           "type" => "binary",
                                           "subproto" => "binary" )

                     #"^\/hdd-server" => ( "host" => "127.0.0.1",
                     #                      "port" => 9998,
                     #                      "proto" => "websocket" ),

                     #"^\/fd-server" => ( "host" => "127.0.0.1",
                     #                      "port" => 9997,
                     #                      "proto" => "websocket" )
                    )
