
[group]
group0=Administrator
group1=Operator
group2=User
group3=OEM1
group4=OEM2
group5=OEM3
group6=OEM4
group7=NA
group8=NA
group9=NA
group10=NA
group11=NA
group12=NA
group13=NA
group14=NA
group15=NA

[group0]
privilege=4
subitempriv=65535
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group1]
privilege=3
subitempriv=65535
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group2]
privilege=2
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group3]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group4]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group5]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group6]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group7]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group8]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group9]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group10]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group11]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group12]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group13]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group14]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

[group15]
privilege=3
subitempriv=3
usercount=0
user0=NA
user1=NA
user2=NA
user3=NA
user4=NA
user5=NA
user6=NA
user7=NA
user8=NA
user9=NA
user10=NA
user11=NA
user12=NA
user13=NA
user14=NA
user15=NA

