# SYSLOG 1
# AUDITLOG 1
# SELLOG 1
local1.*                                /usr/local/log/audit.log
local2.*                                /usr/local/log/sel.log
local3.*                                /extlog/extended.log
*.=info;local1.none;local2.none                     @127.0.0.1
*.=debug;local1.none;local2.none;local3.none		/usr/local/log/debug.log
*.=info;local1.none;local2.none;local3.none			/usr/local/log/info.log
*.=notice;local1.none;local2.none;local3.none		/usr/local/log/notice.log
*.=warning;local1.none;local2.none;local3.none		/usr/local/log/warning.log
*.=err;local1.none;local2.none;local3.none			/usr/local/log/err.log
*.=crit;local1.none;local2.none;local3.none			/usr/local/log/crit.log
*.=alert;local1.none;local2.none;local3.none		/usr/local/log/alert.log
*.=emerg;local1.none;local2.none;local3.none		/usr/local/log/emerg.log
