##set no access for tmp directory
$HTTP["url"] =~ "^/tmp/" {
        url.access-deny = ("")
}

##set no access for SELLog directory
$HTTP["url"] =~ "^/SELlog" {
        url.access-deny = ("")
}

##set no access for config.bak directory
$HTTP["url"] =~ "^/config.bak" {
        url.access-deny = ("")
}

##set no access for InspurGetBlackboxPeciLog directory
$HTTP["url"] =~ "^/InspurGetBlackboxPeciLog/" {
        url.access-deny = ("")
}

##set no access for blackbox directory
$HTTP["url"] =~ "^/blackbox/" {
        url.access-deny = ("")
}
