server.modules    +=      ( "mod_redirect" )
$HTTP["scheme"] == "http" {
$HTTP["host"] =~"^(.*):" {
        url.redirect = ( "^(.*)$" => "https://%0$0" )
}
}
$SERVER["socket"] == ":80" {
  $HTTP["host"] =~ ".*" {
        url.redirect = ( ".*" => "https://%0$0" )
 }
}
